// Auto-generated by gear_data.py — do not edit manually
const GEAR_DATA = {
  "skis": [
    {
      "name": "ARV",
      "brand": "Armada",
      "styles": [
        "groomer",
        "park",
        "all-mountain"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "waist_mm": 94,
      "lengths": [
        164,
        171,
        178,
        185
      ],
      "price": "$649",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100306748_1.png?v=1776914439",
      "notes": "Replace with your real product. Great all-rounder for mixed terrain."
    },
    {
      "name": "Enforcer",
      "brand": "Nordica",
      "styles": [
        "mogul",
        "groomer",
        "all-mountain"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "waist_mm": 94,
      "lengths": [
        167,
        173,
        179,
        185,
        191
      ],
      "price": "$799",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100294730.PetrolGrey.1.png?v=1775604185",
      "notes": "Replace with your real product. Wide and rockered for deep days."
    },
    {
      "name": "Bent Chetler 120",
      "brand": "Atomic",
      "styles": [
        "groomer",
        "powder"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "waist_mm": 120,
      "lengths": [
        176,
        184,
        192
      ],
      "price": "$899.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100306676-MULTI-5.png?v=1775859210",
      "notes": "Replace with your real product. Narrow piste carver."
    },
    {
      "name": "Arcade 78 XPRESS 10 GW",
      "brand": "Rossignol",
      "styles": [
        "groomer",
        "carving"
      ],
      "skill": [
        "beginner",
        "intermediate"
      ],
      "waist_mm": 78,
      "lengths": [
        156,
        164,
        180
      ],
      "image": "https://www.sportsbasement.com/cdn/shop/files/100288831.Arcade78Xpress10GW.1.png?v=1754107583",
      "notes": "This is the ski for the person that is getting off of rentals wanting their own pairs of skis for someone that doesnt go as often a season, this is a groomer friendly ski that is amazing for that and carving."
    },
    {
      "name": "Prodigy 2",
      "brand": "Faction",
      "styles": [
        "park"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "waist_mm": 98,
      "lengths": [
        165,
        171,
        177
      ],
      "price": "679.99",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295823_1.png?v=1766858791",
      "notes": "Fun park ski that does anything you want, if you want more of an all mountain apporach look for the ARV"
    },
    {
      "name": "Prodigy 1",
      "brand": "Faction",
      "styles": [
        "park"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "waist_mm": 88,
      "lengths": [
        164,
        171,
        178,
        184
      ],
      "price": "629.99",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295822_1.png?v=1766857795",
      "notes": "Fun park ski that does anything you want, if you want more of an all mountain apporach look for the ARV"
    }
  ],
  "snowboards": [
    {
      "name": "Hometown Hero",
      "brand": "Burton",
      "styles": [
        "all-mountain",
        "freeride"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "dircetional",
      "flex": 7,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "679.95",
      "image": "https://www.burton.com/static/product/W26/2224513E1QRG_1.png?impolicy=bglt&imwidth=943",
      "notes": "This is a great All Mountain board, it feels stable at high speed. This pairs great with their channel system bindings"
    },
    {
      "name": "Good Company",
      "brand": "Burton",
      "styles": [
        "freestyle",
        "all-mountain"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 4,
      "lengths": [
        135,
        145,
        148,
        152,
        155,
        159
      ],
      "price": "449.95",
      "image": "https://www.burton.com/static/product/W26/2359513A03RG_1.png?impolicy=bglt&imwidth=943",
      "notes": "This is one of the best park boards on the market. Go anywhere on the park with this board."
    },
    {
      "name": "Custom",
      "brand": "Burton",
      "styles": [
        "all-mountain",
        "freestyle",
        "freeride"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 6,
      "lengths": [
        150,
        154,
        156,
        158,
        162
      ],
      "price": "679.95",
      "image": "https://www.burton.com/static/product/W26/106881997DRG_1.png?impolicy=bglt&imwidth=943",
      "notes": "The custom is a great board."
    },
    {
      "name": "Custom X",
      "brand": "Burton",
      "styles": [
        "all-mountain",
        "freeride",
        "freestyle"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 8,
      "lengths": [
        150,
        154,
        156,
        158,
        162
      ],
      "price": "899.95",
      "image": "https://www.burton.com/static/product/W26/106891CA03RG_1.png?impolicy=bglt&imwidth=943",
      "notes": "The custom x is a upgrade from the regular custom, the difference is stiffness. The stifness allows the board to be a hard charger with speed."
    },
    {
      "name": "Team",
      "brand": "Nitro",
      "styles": [
        "all-mountain",
        "freestyle",
        "freeride"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 7,
      "lengths": [
        152,
        155,
        157,
        159,
        162
      ],
      "price": "579.95",
      "image": "",
      "notes": ""
    },
    {
      "name": "T1",
      "brand": "Nitro",
      "styles": [
        "all-mountain",
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 7,
      "lengths": [
        149,
        152,
        155,
        158
      ],
      "price": "529.95",
      "image": "https://www.nitrosnowboards.com/cdn/shop/files/833228-001_T1_149_Product-1.jpg?v=1755928801&width=800",
      "notes": "This board is an amazing all mountain board for those blue bird days that can be taken anywhere. Its least strongest suit is in powder."
    },
    {
      "name": "Alternator",
      "brand": "Nitro",
      "styles": [
        "all-mountain",
        "freeride"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional",
      "flex": 8,
      "lengths": [
        154,
        157,
        160,
        162
      ],
      "price": "579.95",
      "image": "https://www.nitrosnowboards.com/cdn/shop/files/833214-001_Alternator_154_Product-1.jpg?v=1755950251&width=800",
      "notes": "This is that all mountain board that really does all mountain. This can be taken in float, park, etc. (26/27 is the last year of the alt)"
    },
    {
      "name": "Whatever",
      "brand": "Bataleon",
      "styles": [
        "freeride",
        "freestyle",
        "all-mountain"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 5,
      "lengths": [
        138,
        144,
        148,
        151,
        154,
        157
      ],
      "price": "599.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100296294_144.png?v=1761849755",
      "notes": "This is a great board that goes from groomers to steeps without hezzy."
    },
    {
      "name": "Evil Twin",
      "brand": "Bataleon",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 5,
      "lengths": [
        151,
        154,
        157,
        159
      ],
      "price": "579.95",
      "image": "https://bataleon.com/cdn/shop/files/bataleon-2526-eviltwin-2-mens-snowboards.jpg?v=1757387976&width=493",
      "notes": "Bataleons best resort board that we carry, it has a lot of hype around the mountain from the park to steeps."
    },
    {
      "name": "Disaster",
      "brand": "Bataleon",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 3,
      "lengths": [
        144,
        148,
        151,
        154,
        157
      ],
      "price": "499.95",
      "image": "https://bataleon.com/cdn/shop/files/bataleon-2526-disaster-2-mens-snowboards.jpg?v=1757387976&width=493",
      "notes": "Park heavy board that does anything, best for butters or any kind of presses."
    },
    {
      "name": "Goliath+",
      "brand": "Bataleon",
      "styles": [
        "freeride",
        "all-mountain"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 7,
      "lengths": [
        153,
        156,
        159
      ],
      "price": "699.95",
      "image": "https://bataleon.com/cdn/shop/files/bataleon-2526-goliath-plus-2-mens-snowboards_e50c0e08-eddc-470d-b54c-99092098b4b3.jpg?v=1764664626&width=360",
      "notes": "This is going to be their all mountain option that can run down the hill."
    },
    {
      "name": "Dark Horse",
      "brand": "Capita",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 6,
      "lengths": [
        148,
        150,
        152,
        154,
        156,
        158
      ],
      "price": "499.95",
      "image": "https://capitasnowboarding.com/cdn/shop/files/FST03_DARK_HORSE_150_550x550.png?v=1738183696",
      "notes": "This is going to be a park/resort board that is really good at jumps either small to 100 footers."
    },
    {
      "name": "Mercury",
      "brand": "Capita",
      "styles": [
        "freeride",
        "all-mountain",
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 6.5,
      "lengths": [
        147,
        150,
        153,
        155,
        157,
        159,
        161
      ],
      "price": "679.95",
      "image": "https://capitasnowboarding.com/cdn/shop/files/FRD05_MERCURY_147_f704d6fe-b943-47ea-a52c-f2474d32c864_550x550.png?v=1738179265",
      "notes": "Capitas staple in my opinion, cannot go wrong with this board as it does everything great."
    },
    {
      "name": "Aeronaut",
      "brand": "Capita",
      "styles": [
        "freeride"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional",
      "flex": 6,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "699.95",
      "image": "https://capitasnowboarding.com/cdn/shop/files/RST02_AERONAUT_153_9c18bb71-000d-44bb-b0ed-a273060dd713.png?v=1738177827&width=1024",
      "notes": "This directional boards is amazing in the backcountry!"
    },
    {
      "name": "Kazu Kokubo",
      "brand": "Capita",
      "styles": [
        "freeride",
        "all-mountain"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional",
      "flex": 6,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "699.95",
      "image": "https://capitasnowboarding.com/cdn/shop/files/FRD04_KAZU_151_e3c09b6f-11ba-4d7c-a083-993a9d6651e8.png?v=1738178854&width=1024",
      "notes": "Fast and Powerful. This board goes from side-country down to resort once you are done."
    },
    {
      "name": "D.O.A.",
      "brand": "Capita",
      "styles": [
        "freestyle",
        "all-mountain"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 5.5,
      "lengths": [
        148,
        150,
        152,
        154,
        156,
        158,
        160,
        162,
        164
      ],
      "price": "579.95",
      "image": "https://capitasnowboarding.com/cdn/shop/files/RST03_DOA_148_07b6f332-7858-4fdb-8b75-2b0a1b617fb0.png?v=1738178394&width=1024",
      "notes": "D.O.A stands for Destroyer of Awesomeness with this board anything can be done. Really good at going fast and really stable."
    },
    {
      "name": "Horizon",
      "brand": "United Shapes",
      "styles": [
        "all-mountain",
        "freeride",
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 5,
      "lengths": [
        143,
        147,
        151,
        155,
        159
      ],
      "price": "$649",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295818_1.png?v=1766423862",
      "notes": "For those who like simple. Any board from the United Shapes line comes with matte top sheet. This board is for those who want to do everything, this board has no limits.Not to mention the tortional flex this board has allows for quick response."
    },
    {
      "name": "Object",
      "brand": "United Shapes",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "The object is a really niche park board that is not spotted on the regular, this board is really flexy for those who enjoy presses and butters."
    },
    {
      "name": "Deep Reach",
      "brand": "United Shapes",
      "styles": [
        "freeride"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional",
      "flex": 8,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "The Deep Reach is amazing at holding edges, and carving really fun on those powder days."
    },
    {
      "name": "Cadet",
      "brand": "United Shapes",
      "styles": [
        "freeride",
        "carving",
        "all-mountain"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional",
      "flex": 8,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "This board is so amazing at everything, looking for something that does everything this is the one (We had a customer heli ride in this). The stiffness on this boardallows it to be stable at high speeds, the edge control is instant this board wants to move."
    },
    {
      "name": "Orca",
      "brand": "Lib Tech",
      "styles": [
        "freeride",
        "all-mountain"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional",
      "flex": 7,
      "lengths": [
        144,
        147,
        150,
        153,
        156,
        159,
        162
      ],
      "price": "$749",
      "image": "https://www.lib-tech.com/media/catalog/product/cache/bd322120d976889db2881a06b8dbba23/2/0/2026-2027-Lib-Tech-Trice-ORCA-II-Snowboard-2400x2400.jpg",
      "notes": "Directonal board that does everything from groomers down to powder, this is an everday board that you cannot get enough from."
    },
    {
      "name": "DPR",
      "brand": "Lib Tech",
      "styles": [
        "all-mountain",
        "freeride",
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 6,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$499",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    },
    {
      "name": "Sleepwalker",
      "brand": "Salomon",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 5,
      "lengths": [
        148,
        151,
        153,
        155,
        158
      ],
      "price": "$449",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100287400_1.png?v=1746804963",
      "notes": "True twin that is ready for any rails, this board is mid stiff great entry level board into the sport as well"
    },
    {
      "name": "Huck Knife",
      "brand": "Salomon",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 6,
      "lengths": [
        148,
        151,
        153,
        155,
        158
      ],
      "price": "$579.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100303307_1.png?v=1778699861",
      "notes": "True twin that is ready for any rails, this board is mid stiff great entry level board into the sport as well"
    },
    {
      "name": "Huck Knife Pro",
      "brand": "Salomon",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 7,
      "lengths": [
        138,
        143,
        147,
        151,
        153,
        155,
        158
      ],
      "price": "$679.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100303306_1.png?v=1778699095",
      "notes": "True twin that is ready for any rails, this board is mid stiff great entry level board into the sport as well"
    },
    {
      "name": "Abstract",
      "brand": "Salomon",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 5,
      "lengths": [
        138,
        143,
        147,
        151,
        153,
        155,
        158
      ],
      "price": "$549.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100303308_1.png?v=1778710493",
      "notes": "True twin that is ready for any rails, this board is mid stiff great entry level board into the sport as well"
    },
    {
      "name": "Assasin",
      "brand": "Salomon",
      "styles": [
        "all-mountain",
        "freeride",
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$649.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100303301_1.png?v=1778690327",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    },
    {
      "name": "Assasin Pro",
      "brand": "Salomon",
      "styles": [
        "all-mountain",
        "freeride",
        "freestyle"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100303300_1.png?v=1778689126",
      "notes": "699.95"
    },
    {
      "name": "Craft",
      "brand": "Salomon",
      "styles": [
        "all-mountain"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 4,
      "lengths": [
        150,
        153,
        155,
        157,
        158,
        160,
        162
      ],
      "price": "$479.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100303303_1.png?v=1778697728",
      "notes": "."
    },
    {
      "name": "Dancehaul",
      "brand": "Salomon",
      "styles": [
        "freeride"
      ],
      "skill": [
        "intermediate",
        "advanced"
      ],
      "shape": "directional",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "549.95",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100303302_1.png?v=1778697239",
      "notes": "."
    },
    {
      "name": "Tweaker",
      "brand": "Jones",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    },
    {
      "name": "Rally Cat",
      "brand": "Jones",
      "styles": [
        "freestyle",
        "all-mountain",
        "freeride"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "directional-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    },
    {
      "name": "Frontier 2.0",
      "brand": "Jones",
      "styles": [
        "freeride"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    },
    {
      "name": "Storm Wolf",
      "brand": "Jones",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    },
    {
      "name": "Free Carver",
      "brand": "United Shapes",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    },
    {
      "name": "Howler",
      "brand": "Jones",
      "styles": [
        "freestyle"
      ],
      "skill": [
        "beginner",
        "intermediate",
        "advanced"
      ],
      "shape": "true-twin",
      "flex": 4,
      "lengths": [
        144,
        148,
        152,
        156,
        160
      ],
      "price": "$599",
      "image": "https://www.sportsbasement.com/cdn/shop/files/100295816_1.png?v=1766425330",
      "notes": "Matte color to avoid having a shark or a bannana printed on your board, a niche board that holds a lot of fun."
    }
  ]
};
