# ============================================================
#  gear_data.py — MountainFit Product Database
# ============================================================
# 26/27 skis and snowboards, but if images are not found
# resolving by using 25/26 images.
# ============================================================
 
import json
 
# ────────────────────────────────────────────────────────────
#  SKIS
#  styles options : "all-mountain" | "groomer" | "powder" | "park" | "mogul"
#  skill options  : "beginner" | "intermediate" | "advanced"
# ────────────────────────────────────────────────────────────

# TO-DO 1: Add all the skis we sell in store, if images are not found for 26/27 using 25/26 images.

SKIS = [
    # All Mountain Options
    {
        "name": "ARV",
        "brand": "Armada",
        "styles": ["groomer", "park", "all-mountain"],
        "skill": ["intermediate", "advanced"],
        "waist_mm": 94, 
        "lengths": [164, 171, 178, 185],
        "price": "$649",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306748_1.png?v=1776914439",
        "notes": "Replace with your real product. Great all-rounder for mixed terrain."
    },
    {
        "name": "Enforcer",
        "brand": "Nordica",
        "styles": ["mogul", "groomer", "all-mountain"],
        "skill": ["intermediate", "advanced"],
        "waist_mm": 94,
        "lengths": [167, 173, 179, 185, 191],
        "price": "$799",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100294730.PetrolGrey.1.png?v=1775604185",
        "notes": "Replace with your real product. Wide and rockered for deep days."
    },
    {
        "name": "Bent Chetler 120",
        "brand": "Atomic",
        "styles": ["groomer", "powder"],
        "skill": ["intermediate", "advanced"],
        "waist_mm": 120,
        "lengths": [176, 184, 192],
        "price": "$899.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306676-MULTI-5.png?v=1775859210",
        "notes": "Replace with your real product. Narrow piste carver."
    },
    # Groomed Runs/Beginner Options as well
    {
        "name": "Arcade 78 XPRESS 10 GW",
        "brand": "Rossignol",
        "styles": ["groomer", "carving"],
        "skill": ["beginner", "intermediate"],
        "waist_mm": 78,
        "lengths": [156, 164, 180],
        "image": "https://www.sportsbasement.com/cdn/shop/files/100288831.Arcade78Xpress10GW.1.png?v=1754107583",
        "notes": "This is the ski for the person that is getting off of rentals wanting their own pairs of skis for someone that doesnt go as often a season, this is a groomer friendly ski that is amazing for that and carving."
    },
    # Park Options
    {
        "name": "Prodigy 2",
        "brand": "Faction",
        "styles": ["park"],
        "skill": ["intermediate", "advanced"],
        "waist_mm": 98,
        "lengths": [165, 171, 177],
        "price": "679.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100295823_1.png?v=1766858791",
        "notes": "Fun park ski that does anything you want, if you want more of an all mountain apporach look for the ARV"
    },
    {
        "name": "Prodigy 1",
        "brand": "Faction",
        "styles": ["park"],
        "skill": ["intermediate", "advanced"],
        "waist_mm": 88,
        "lengths": [164, 171, 178, 184],
        "price": "629.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100295822_1.png?v=1766857795",
        "notes": "Fun park ski that does anything you want, if you want more of an all mountain apporach look for the ARV"
    }
]
  
# ── DO NOT EDIT BELOW ───────────────────────────────────────
 
def export():
    data = {"skis": SKIS, "snowboards": SNOWBOARDS}
    js = "// Auto-generated by gear_data.py — do not edit manually\n"
    js += "const GEAR_DATA = " + json.dumps(data, indent=2) + ";\n"
    with open("gear_data.js", "w") as f:
        f.write(js)
    print(f"✅  Exported {len(SKIS)} skis and {len(SNOWBOARDS)} snowboards → gear_data.js")
    print("    Put gear_data.js in the same folder as mountainfit.html")
 
if __name__ == "__main__":
    export()